prjMvcCoreDemo/Controllers/CustomerController.cs
using Microsoft.AspNetCore.Mvc;
using prjMvcCoreDemo.Models;
using prjMvcCoreDemo.ViewModels;

namespace prjMvcCoreDemo.Controllers
{
    public class CustomerController : SuperController
    {
        public IActionResult List(CKeywordViewModel vm)
        {
            DbDemoContext context = new DbDemoContext();
            IEnumerable<TCustomer> datas = null;
            if(vm.txtKeyword ==null)
                datas = from t in context.TCustomers
                        select t;
            else
                datas = context.TCustomers.Where(t => t.FName.ToUpper().Contains(vm.txtKeyword.ToUpper())
                || t.FPhone.ToUpper().Contains(vm.txtKeyword.ToUpper())
                || t.FEmail.ToUpper().Contains(vm.txtKeyword.ToUpper())
                || t.FAddress.ToUpper().Contains(vm.txtKeyword.ToUpper())
                );
            return View(datas);
        }
        public IActionResult Create()
        { 
            return View();
        }
        [HttpPost]
        public IActionResult Create(TCustomer c)
        {
            DbDemoContext ctx = new DbDemoContext();
            ctx.TCustomers.Add(c);
            ctx.SaveChanges();

            return RedirectToAction("List");
        }
        public IActionResult Delete(int? id)
        {
            if (id != null)
            {
                DbDemoContext ctx = new DbDemoContext();
                TCustomer pro = ctx.TCustomers.FirstOrDefault(p => p.Fid == id);
                if (pro != null)
                {
                    ctx.TCustomers.Remove(pro);
                    ctx.SaveChanges();
                }
            }
            return RedirectToAction("List");
        }
        public IActionResult Edit(int? id)
        {
            if (id == null)
                return RedirectToAction("List");
            DbDemoContext ctx = new DbDemoContext();
            TCustomer cust = ctx.TCustomers.FirstOrDefault(p => p.Fid == id);
            if (cust == null)
                return RedirectToAction("List");
            return View(cust);
        }
        [HttpPost]
        public IActionResult Edit(TCustomer pln)
        {
            DbDemoContext ctx = new DbDemoContext();
            TCustomer cust = ctx.TCustomers.FirstOrDefault(p => p.Fid == pln.Fid);
            if (cust != null)
            {
                cust.FName = pln.FName;
                cust.FPhone = pln.FPhone;
                cust.FEmail = pln.FEmail;
                cust.FAddress = pln.FAddress;
                cust.FPassword = pln.FPassword;
                ctx.SaveChanges();
            }
            return RedirectToAction("List");
        }
    }
}

prjMvcCoreDemo/Controllers/ProductController.cs
using Microsoft.AspNetCore.Mvc;
using prjMauiDemo.NewFolder2;
using prjMvcCoreDemo.Models;
using prjMvcCoreDemo.ViewModels;

namespace prjMvcCoreDemo.Controllers
{
    public class ProductController : SuperController
    {
        private IWebHostEnvironment _enviro = null;

        public ProductController(IWebHostEnvironment p)
        {
            _enviro = p;
        }
        public IActionResult List(CKeywordViewModel vm)
        {
            DbDemoContext cxt = new DbDemoContext();
            IEnumerable<TProduct> datas = null;
            if (vm.txtKeyword == null)
                datas = from t in cxt.TProducts
                        select t;
            else
                datas = cxt.TProducts.Where(t => t.FName.ToUpper().Contains(vm.txtKeyword.ToUpper())
                );
            return View(datas);
        }
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Create(TProduct c)
        {
            DbDemoContext ctx = new DbDemoContext();
            ctx.TProducts.Add(c);
            ctx.SaveChanges();

            return RedirectToAction("List");
        }
        public IActionResult Delete(int? id)
        {
            if (id != null)
            {
                DbDemoContext ctx = new DbDemoContext();
                TProduct prod = ctx.TProducts.FirstOrDefault(p => p.FId == id);
                if (prod != null)
                {
                    ctx.TProducts.Remove(prod);
                    ctx.SaveChanges();
                }
            }
            return RedirectToAction("List");
        }
        public IActionResult Edit(int? id)
        {
            if (id == null)
                return RedirectToAction("List");
            DbDemoContext ctx = new DbDemoContext();
            TProduct prod = ctx.TProducts.FirstOrDefault(p => p.FId == id);
            if (prod == null)
                return RedirectToAction("List");
            CProductWrap prodWrap = new CProductWrap();
            prodWrap.product = prod;
            return View(prodWrap);
        }
        [HttpPost]
        public IActionResult Edit(CProductWrap pln)
        {
            DbDemoContext ctx = new DbDemoContext();
            TProduct prod = ctx.TProducts.FirstOrDefault(p => p.FId == pln.FId);
            if (prod != null)
            {
                if(pln.photo != null)
                {
                    string photoName = Guid.NewGuid().ToString() + ".jpg"; //Guid建立亂數，可避免存放進去的照片出現相同的檔名
                    prod.FImagePath = photoName; //放到我們資料庫中ImagePath 做為路徑
                    //這段則是mvcCore最大的不同，改使用CopyTo(),裡面再用FileStream(照片的路徑, 如果找不到就新增)
                    pln.photo.CopyTo(new FileStream(
                        _enviro.WebRootPath + "/images/" + photoName, FileMode.Create));//WebRootPath 可以幫我們導到wwwroot
                }

                prod.FName = pln.FName;
                prod.FQty = pln.FQty;
                prod.FPrice = pln.FPrice;
                prod.FCost = pln.FCost;
                ctx.SaveChanges();
            }
            return RedirectToAction("List");
        }

    }
}

prjMvcCoreDemo/Controllers/ShoppingController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.CodeAnalysis.CSharp.Syntax;
//using Newtonsoft.Json;
using prjMvcCoreDemo.Models;
using prjMvcCoreDemo.ViewModels;
using System.Text.Json;

namespace prjMvcCoreDemo.Controllers
{
    public class ShoppingController : SuperController
    {
        public IActionResult CartView()
        {
            if (!HttpContext.Session.Keys.Contains(CDictionary.SK_PURCHASED_PRODUCTS_LIST))
                return RedirectToAction("List");

            string  json = HttpContext.Session.GetString(CDictionary.SK_PURCHASED_PRODUCTS_LIST);
            List<CShoppingCartItem> cart = JsonSerializer.Deserialize<List<CShoppingCartItem>>(json);
            return View(cart);
        }
        public IActionResult List()
        {
            DbDemoContext ctx = new DbDemoContext();
            var datas = from p in ctx.TProducts
                        select p;
            return View(datas);
        }
        public IActionResult AddToCart(int? id)
        {
            if (id == null)
                return RedirectToAction("List");
            ViewBag.FID = id;
            return View();
        }
        [HttpPost]
        public IActionResult AddToCart(CAddToCartViewModel vm)
        {
            DbDemoContext ctx = new DbDemoContext();
            TProduct prod = ctx.TProducts.FirstOrDefault(p => p.FId == vm.txtFId);
            if (prod != null)
            {
                string json = "";
                List<CShoppingCartItem> cart = null;
                if (HttpContext.Session.Keys.Contains(CDictionary.SK_PURCHASED_PRODUCTS_LIST))
                {
                    json = HttpContext.Session.GetString(CDictionary.SK_PURCHASED_PRODUCTS_LIST);
                    cart = JsonSerializer.Deserialize<List<CShoppingCartItem>>(json);
                }
                else
                    cart = new List<CShoppingCartItem>();
                CShoppingCartItem item = new CShoppingCartItem();
                item.price = (decimal)prod.FPrice;
                item.count = vm.txtCount;
                item.productId = vm.txtFId;
                item.Product = prod;
                cart.Add(item);
                json=JsonSerializer.Serialize(cart);
                HttpContext.Session.SetString(CDictionary.SK_PURCHASED_PRODUCTS_LIST, json);
            }
            return RedirectToAction("List");
        }


    }
}

prjMvcCoreDemo/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - prjMvcCoreDemo</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/prjMvcCoreDemo.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Login">prjMvcCoreDemo賣場</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Customer" asp-action="List">客戶資料</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Product" asp-action="List">商品管理</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Shopping" asp-action="List">購物</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - prjMvcCoreDemo - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>